config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :locations, only: [:create]
      resources :destinations, only: [:create]
      resources :users, only: [:create]
      resources :posts, only: [:create]
    end
  end

  root to: 'home#home'
  resources :posts
  resources :locations
  resources :users
  get 'refugee_search', to: 'pages#refugee_search'
  get 'refugee_show', to: 'pages#refugee_show'
  get 'government', to: 'pages#government'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
end

app/models/post.rb
class Post < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
  has_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :locations
  has_many :destinations
end

app/controllers/api/v1/locations_controller.rb
# class Api::V1::LocationsController < ApplicationController
# end
module Api
  module V1
    class LocationsController < ApplicationController
      skip_before_filter  :verify_authenticity_token

      def create
        user = User.find(params[:user_id])
        location = user.locations.create(address: params[:address], latitude: params[:latitude], longitude: params[:longitude])
        if location.save
           render :json => {:status => 200}.to_json
        end
      end
    end
  end
end

app/controllers/api/v1/posts_controller.rb
# class Api::V1::PostsController < ApplicationController
# end
module Api
  module V1
    class PostsController < ApplicationController
      skip_before_filter  :verify_authenticity_token

      def create
        post = Post.create(message: params[:message], latitude: params[:latitude], longitude: params[:longitude])
        Indico.api_key = '6b911bcc3dc867c5d5b9946b2f5b3345'
        post.positivity = Indico.sentiment(post.message)
        keyword_hash = Indico.keywords(post.message)
        keyword_hash.each do |key, value|
          post.tags.create(word: key, latitude: post.latitude, longitude: post.longitude)
        end
        if post.save
          render json: {status: 200}
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def create

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def government
    @posts = Post.all.limit(100)
    @users = User.all.limit(100)

    # keywords
    @berlin_tags = most_common(Tag.near("Berlin", 150).map {|n| n.word})
    @istanbul_tags = most_common(Tag.near("Istanbul", 150).map {|n| n.word})
    @toronto_tags = most_common(Tag.near("Toronto", 150).map {|n| n.word})
  end

  def refugee_search
  end

  def refugee_show
    @user = User.find_by(name: params[:name])
    if @user.blank?
      flash[:danger] = "User not found"
      redirect_to(:back)
      return
    end
  end

  private

  def most_common posts
    url_count = posts.each_with_object(Hash.new(0)) do |item, count|
      count[item] += 1
    end
    top_urls = url_count.keys.sort_by!{|url| url_count[url]}.last(5).reverse!
    return top_urls
  end
end

app/controllers/posts_controller.rb
require 'indico'
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  def create
    post = Post.create(message: params[:message], latitude: request.location.latitude, longitude: request.location.longitude)
    if post.save
      flash[:success] = "You've successfully made a post!"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.create(name: params[:user][:name])
    if user.save
      flash[:success] = "Successfully created a new user"
      redirect_to action: "index"
    end
  end
end

app/helpers/api/v1/destinations_helper.rb
module Api::V1::DestinationsHelper
end

app/helpers/api/v1/locations_helper.rb
module Api::V1::LocationsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
    <p id="notice"><%= notice %></p>

    <h1>Listing Locations</h1>

    <table>
      <thead>
        <tr>
          <th>Address</th>
          <th>Latitude</th>
          <th>Longitude</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @locations.each do |location| %>
          <tr>
            <td><%= location.address %></td>
            <td><%= location.latitude %></td>
            <td><%= location.longitude %></td>
            <td><%= link_to 'Show', location %></td>
            <td><%= link_to 'Edit', edit_location_path(location) %></td>
            <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Location', new_location_path %>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>